ALL_TICKERS = [
    'C:AUDCAD', 'C:AUDJPY', 'C:AUDNZD', 'C:AUDUSD', 'C:CADCHF',
    'C:CADJPY', 'C:CHFJPY', 'C:EURAUD', 'C:EURCAD', 'C:EURCHF', 'C:EURGBP',
    'C:EURJPY', 'C:EURNOK', 'C:EURNZD', 'C:EURPLN', 'C:EURSGD',
    'C:EURUSD', 'C:GBPAUD', 'C:GBPCAD', 'C:GBPCHF', 'C:GBPJPY',
    'C:GBPNZD', 'C:GBPUSD', 'C:NZDCAD', 'C:NZDCHF', 'C:NZDJPY', 'C:NZDUSD',
    'C:USDCAD', 'C:USDCHF', 'C:USDJPY', 'C:USDMXN', 'C:USDNOK', 'C:USDSEK',
    'C:USDSGD', 'C:USDZAR'
]
ALL_TICKERS = list(set(ALL_TICKERS))